[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
watchPatterns = [
    "Requirements.txt", 
    "src/**", 
    "railway.toml",
    "Dockerfile",
]

[deploy]
region = "us-west2"
runtime = "V2"
numReplicas = 1
sleepApplication = false
multiRegionConfig = {"us-west2":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
